language: java
install: true

jdk:
  - oraclejdk8

before_script:
  - cd $TRAVIS_BUILD_DIR
  - rm -rf ./src/test/resources/test.h2.db

script:
  - ./gradlew build --scan -s

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

env:
  - QURIES_PATH=$TRAVIS_BUILD_DIR/src/test/resources/sql

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash) -t be62456b-0be6-4b5d-825c-23664fb1ce84